In [2]:
import nbformat
from nbconvert import HTMLExporter
import os

In [3]:
def convert(file):

    with open(file, "r", encoding="utf-8") as f:
        nb_node = nbformat.read(f, as_version=4)

    html_exporter = HTMLExporter()
    body, _ = html_exporter.from_notebook_node(nb_node)
    name = file[::-1].split(".",1)[-1][::-1]
    with open(f"./{name}.html", "w", encoding="utf-8") as f:
        f.write(body)

In [6]:
for i in os.listdir():
    # if i.endswith(".ipynb") and i.startswith("tmp") == False:
    if i.endswith("7.ipynb"):
        print(i)
        convert(i)

7.ipynb

/home/mubeen/venv/gpu/lib/python3.10/site-packages/nbconvert/filters/highlight.py:71: UserWarning: No lexer found for language 'text/markdown'. Treating as plain text.
  return _pygments_highlight(
/home/mubeen/venv/gpu/lib/python3.10/site-packages/nbconvert/filters/highlight.py:71: UserWarning: No lexer found for language 'text/markdown'. Treating as plain text.
  return _pygments_highlight(
/home/mubeen/venv/gpu/lib/python3.10/site-packages/nbconvert/filters/highlight.py:71: UserWarning: No lexer found for language 'text/markdown'. Treating as plain text.
  return _pygments_highlight(
/home/mubeen/venv/gpu/lib/python3.10/site-packages/nbconvert/filters/highlight.py:71: UserWarning: No lexer found for language 'text/markdown'. Treating as plain text.
  return _pygments_highlight(
/home/mubeen/venv/gpu/lib/python3.10/site-packages/nbconvert/filters/highlight.py:71: UserWarning: No lexer found for language 'text/markdown'. Treating as plain text.
  return _pygments_highlight(
/home/mubeen/venv/gpu/lib/python3.10/site-packages/nbconvert/filters/highlight.py:71: UserWarning: No lexer found for language 'text/markdown'. Treating as plain text.
  return _pygments_highlight(
/home/mubeen/venv/gpu/lib/python3.10/site-packages/nbconvert/filters/highlight.py:71: UserWarning: No lexer found for language 'text/markdown'. Treating as plain text.
  return _pygments_highlight(
/home/mubeen/venv/gpu/lib/python3.10/site-packages/nbconvert/filters/highlight.py:71: UserWarning: No lexer found for language 'text/markdown'. Treating as plain text.
  return _pygments_highlight(
/home/mubeen/venv/gpu/lib/python3.10/site-packages/nbconvert/filters/highlight.py:71: UserWarning: No lexer found for language 'text/markdown'. Treating as plain text.
  return _pygments_highlight(

In [20]:
import json

In [45]:
with open(file, 'r') as f:
    js = json.load(f)

# Function to recursively update each dict jo 'url' rakhta hai
def add_html_key(obj):
    if isinstance(obj, dict):
        # Agar 'url' key hai to 'html' key bhi add kar do
        if 'url' in obj:
            obj['html'] = obj['url'].replace("https://nbviewer.org/github/","https://htmlpreview.github.io/?https://github.com/").replace("ipynb","html")
        # Recursively sub-dictionaries ya lists me bhi call karo
        for k, v in obj.items():
            add_html_key(v)
    elif isinstance(obj, list):
        for item in obj:
            add_html_key(item)

# JSON ke root me call kar do
add_html_key(js)
with open(file, 'w') as f_out:
    json.dump(js, f_out, indent=4)

{'courses': {'functional_programming': {'topic_name': 'Functional Python Programming',
   'description': 'Master the art of writing clean, efficient code using functional paradigms.',
   'url': 'functional_programming.html',
   'subtopics': {'Function': {'topic_name': 'Function',
     'description': '- What is Function<br>- What is return Statement<br>- What is Nested Function<br>- *args and  **kwargs<br>- default Argument',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/0.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/0.ipynb'},
    'refference': {'topic_name': 'Pass By Value or Refference',
     'description': '- Immutable Object (Support as Pass by Value)<br>- mutable Object (Support as Pass by Refference)',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/0.1.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/0.1.ipynb'},
    'lambda_doc': {'topic_name': 'Lambda Function and Docstring',
     'description': '- lambda Anonmyous<br>- What is Docstring<br>- What should be included in a docstring?',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/0.2.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/0.2.ipynb'},
    'namespace': {'topic_name': 'Namespaces LEGB Rule',
     'description': '- Local Scope<br>- Global Scope<br>- Enclosing / Non Local Scope<br>- Built-In Scope<br>- local and global keyword<br>- locals and globals Function',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/0.3.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/0.3.ipynb'},
    'iter_iterable': {'topic_name': 'Iterables and Iterators',
     'description': '- What is Iterable (Sequential Data Types)<br>- Iterators (Convert iterable into Iterator for iterate)<br>- iter() Function (convert iterable to iterator)<br>- next() Function (Iterations)<br>- Sequential Process (User Single Value at 1 time)<br>-  Is All Iterables are Iterators ? (No)<br>- Identify Iterators (with collections.abc.Iterable with isinstance function)<br>- itertools.chain() Method<br>- itertools.permutations() Method<br>- itertools.combinations() Method<br>- itertools.accumulate() Method<br>- itertools.cycle() Method<br>- zip Function<br>- enumerate() Function',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/10.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/10.ipynb'},
    'Generators': {'topic_name': 'Generators',
     'description': '- What is Generators (Special Type of Iterator)<br>- Concept of Yield<br>- Concept of Pause and Resume<br>- Sender and Reciver Concept(.send Method)<br>- next() and .send<br>- Throw Error outside (.throw Method)<br>- Close Generator (.close Method)<br>- Normal Iterators Vs Generators<br>- Generaters Vs Function',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/11.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/11.ipynb'},
    'Comprehensions ': {'topic_name': 'Comprehensions ',
     'description': '- List Comprehensions<br>- Set Comprehensions<br>- Dictionary Comprehensions<br>- Generator Comprehensions',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/12.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/12.ipynb'},
    'introduction': {'topic_name': 'Introduction of Functional Programming',
     'description': '- An overview of Functional programming principles.<br>- Imperative vs Functional Paradigm<br>- Advantages',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/1.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/1.ipynb'},
    'pure_and_impure_functions': {'topic_name': 'Pure & Impure Function',
     'description': '- Pure Function<br>- Impure (Normal) Function',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/2.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/2.ipynb'},
    'higher_order_functions': {'topic_name': 'First Class & Higher Order Function',
     'description': '- First Class Function<br>- Assign Function in the Variable<br>- Higher Order Function<br>- Pass Function as a Argument and Call Function With The Argument<br>- Function Return Other Function and Call it Outside',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/3.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/3.ipynb'},
    'close_function': {'topic_name': 'Closure Function',
     'description': '- What is Closure Function<br> - All Clouser Function is also a Higher Order Function<br>- But All Higher Order Function are Not a Clouser Function',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/4.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/4.ipynb'},
    'bulitin_hof1': {'topic_name': 'Bulit-In Higher Order Function 1 (Functools) ',
     'description': '- Partial Function (Fix Argument Value)<br>- Reduce Function (Single Value Return)<br>- Map Function(Apply operation)<br>- Filter Function(Select True Value)<br>- cmp_to_key Function (Use with Sorted as a Custom Logic)',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/5.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/5.ipynb'},
    'dec': {'topic_name': 'Decorators ',
     'description': '- What is Decorators<br>- @ Syntax<br>- All Decorators is a HOF<br>- But All HOF are Not a Decorators<br>- Where we Used Decorators<br>- Multiple Decorators<br>- Parameters in Decorators (Multi-Level Used only if Parameter required directly in Decorators)<br>- Arags and Kwargs in Decorators Function',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/6.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/6.ipynb'},
    'bulitin_hof2': {'topic_name': 'Bulit-In Higher Order Function 2 (Functools) ',
     'description': '- wraps Function (Copy Metadata of Orignal Function)<br>- singledispatch Function (Change the Function Behavior for Different DataType)<br>- lru_cache Function(Store Recently Use Values)',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/7.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/7.ipynb'},
    'topic8': {'topic_name': 'Currying and Composition',
     'description': '- Curring (Just Divide Multiple Arguments into Nested Functions)<br>- Composition (Just Pass Functions into Single Function and Create a New Function)<br>- Concept of HOF<br>- Concept of  Closure<br>- Concept of Decorator<br>- Concept of Currying<br>- Concept of Composition',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/8.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/8.ipynb'},
    'topic9': {'topic_name': 'Recursion',
     'description': '- What is Recursion<br>- Base Case and Recursive Case<br>- Direct Recursion<br>- InDirect Recursion<br>- Tail Recursion<br>- Tree Recursion<br>- Nested Recursion<br>- Common Mistakes in Recursion',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/9.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/9.ipynb'},
    'project1': {'topic_name': 'Mini Project',
     'description': '- Create a Login System<br>- Manage Tokens and Sessions<br>- Manage Validations With Decorators<br>- Use Generator For Send a Messages',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/project1.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/Functional_Programming/blob/main/project1.ipynb'}},
   'html': 'html/functional_programming.html'},
  'dsa': {'topic_name': 'DSA Python',
   'description': 'Explore DSA that provides efficient ways to store and process data, covering sorting, searching, recursion, graphs, trees, and optimization algorithms.',
   'url': 'dsa.html',
   'subtopics': {'t1': {'topic_name': 'Scalar, Vector, Array, and Tensors',
     'description': '- What is Scalar (Single Value)<br>- What is Vector (1-D)<br>- What is Array (n-D)<br>- What is Tensors (n-D)',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/DSA/blob/main/1.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/DSA/blob/main/1.ipynb'},
    't2': {'topic_name': 'Data Structures and Types',
     'description': '- Primitive and Non- Primitive Data Types<br>- Linear Data Structure<br>- Non Linear Data Structures',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/DSA/blob/main/2.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/DSA/blob/main/2.ipynb'},
    't3': {'topic_name': 'Arrays Data Structures',
     'description': '- Arrays Data Structures<br>- Linear Data Structure<br>- Contiguous Memory Address<br>- Fix (Static) and Dynamic Size Array<br>- Homogeneous vs Non-Homogeneous',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/DSA/blob/main/3.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/DSA/blob/main/3.ipynb'},
    't4': {'topic_name': 'Arrays CRUD Operations',
     'description': '- Create Array (Insertion in Array)<br>- Read (Traversal in Array)<br>- Update (Modification in Array)<br>- Delete (Remove an Element)',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/DSA/blob/main/4.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/DSA/blob/main/4.ipynb'},
    't5': {'topic_name': 'Linked List',
     'description': '- What is Linked List(Connect Two or More Nodes)<br>- Static and Dynamic Linked list<br>- Node , Head , Tail<br>-  Example 1 Inserting Node at Start<br>- Example 2 Inserting Node at the End<br>- Example 3 Track and Count Nodes<br>- Example 4 Inserting Node at the Mid',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/DSA/blob/main/5.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/DSA/blob/main/5.ipynb'},
    't6': {'topic_name': 'Types of Linked List',
     'description': '- Single<br>- Double<br>- Circular',
     'url': 'https://nbviewer.org/github/Mubeen-Ahmad/DSA/blob/main/6.ipynb',
     'html': 'html/https://nbviewer.org/github/Mubeen-Ahmad/DSA/blob/main/6.ipynb'}},
   'html': 'html/dsa.html'},
  'deep_learning': {'topic_name': 'Deep Learning',
   'description': 'Dive into neural networks and cutting-edge AI techniques.',
   'url': 'deep_learning.html',
   'html': 'html/deep_learning.html'},
  'python': {'topic_name': 'Python for Data Science',
   'description': 'Enhance your Python skills for data analysis and visualization.',
   'url': 'python.html',
   'html': 'html/python.html'}}}

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("/media/mubeen/Others Data { Disk 0 }/Softwere_Changes/database/backup/r.csv")

In [6]:
df.groupby(by=["ward","freq_type"])

In [12]:
df["freq_type"].unique()

array(['Freeze', 'Others'], dtype=object)

In [11]:
# Replace specific values with 'Freeze'
df["freq_type"] = df["freq_type"].replace(["Aquifer,  O F", "Aquifer 1F", "Freze & 0F"], "Freeze")

In [13]:
df

,account_no,freq_type,paid,ward,cell,demand,arrears,con_type,type,pic,time,paid_date,date
0,1090512,Freeze,5000,397,NaN,2888,85614,water_sewer,domestic,/media/mubeen/Others Data { Disk 0 }/Softwere_...,04:42 PM,30-04-2025,02-05-2025
1,90580819,Freeze,10000,177,NaN,2500,118083,Aquifer,commercial,/media/mubeen/Others Data { Disk 0 }/Softwere_...,04:45 PM,02-05-2025,02-05-2025
2,57671981,Freeze,20000,356,NaN,7630,46666,water_sewer,commercial,/media/mubeen/Others Data { Disk 0 }/Softwere_...,04:45 PM,01-05-2025,02-05-2025
3,57900436,Freeze,17250,177,NaN,1219,17150,water_sewer,domestic,/media/mubeen/Others Data { Disk 0 }/Softwere_...,04:46 PM,02-05-2025,02-05-2025
4,27240962,Freeze,4000,175,NaN,1558,13326,water_sewer,domestic,/media/mubeen/Others Data { Disk 0 }/Softwere_...,04:47 PM,30-04-2025,02-05-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993,27199154,Freeze,3000,175,NaN,1219,22598,water_sewer,domestic,/media/mubeen/Others Data { Disk 0 }/Softwere_...,09:11 PM,23-05-2025,23-05-2025
1994,90224212,Freeze,133300,357,NaN,133300,4833165,Aquifer,commercial,/media/mubeen/Others Data { Disk 0 }/Softwere_...,09:14 PM,23-05-2025,23-05-2025
1995,90164813,Freeze,133300,357,NaN,133300,5145380,Aquifer,commercial,/media/mubeen/Others Data { Disk 0 }/Softwere_...,09:14 PM,23-05-2025,23-05-2025
1996,92224225,Freeze,143500,357,NaN,143500,5266768,Aquifer,commercial,/media/mubeen/Others Data { Disk 0 }/Softwere_...,09:15 PM,23-05-2025,23-05-2025
1997,92164826,Freeze,143500,357,NaN,143500,2864473,Aquifer,commercial,/media/mubeen/Others Data { Disk 0 }/Softwere_...,09:16 PM,23-05-2025,23-05-2025

In [26]:
df[df["freq_type"] != "Freeze"].groupby(by=["ward","freq_type"]).agg(Count=('ward','count'),Paid=("paid","sum")).reset_index()

    ward freq_type  Count    Paid
0    142    Others     15  180564
1    143    Others     53  248983
2    144    Others     41  292363
3    146    Others     57  308409
4    147    Others     79  377020
5    175    Others     41  247090
6    177    Others     71  445733
7    356    Others     18  149105
8    357    Others     31  199020
9    360    Others      1    3430
10   365    Others     67  454310
11   367    Others     28  136600
12   368    Others    123  655820
13   397    Others     80  432042

In [21]:
df.groupby(by=["ward","freq_type"]).agg(Count=('ward','count'),Paid=("paid","sum")).reset_index()

    ward freq_type  Count     Paid
0    142    Freeze     58   634350
1    142    Others     15   180564
2    143    Freeze    103   622005
3    143    Others     53   248983
4    144    Freeze    140   949000
5    144    Others     41   292363
6    146    Freeze     62   310400
7    146    Others     57   308409
8    147    Freeze    125   565640
9    147    Others     79   377020
10   175    Freeze    104   889881
11   175    Others     41   247090
12   177    Freeze    112  1505270
13   177    Others     71   445733
14   356    Freeze     60   965301
15   356    Others     18   149105
16   357    Freeze    129  1552393
17   357    Others     31   199020
18   360    Others      1     3430
19   362    Freeze      1     7630
20   365    Freeze     78   573560
21   365    Others     67   454310
22   367    Freeze     97  1284555
23   367    Others     28   136600
24   368    Freeze    114   930320
25   368    Others    123   655820
26   397    Freeze    110   857817
27   397    Others     80   432042